pipeline {
    agent {
        label 'MyProjectAgent'
    }

    tools {
       maven 'Maven3.9.8'
    }

    // Since our pom.xml is not located in our default directory, we need to redefine a directory.
    environment {
       PROJECT_DIR = '/home/jenkins/workspace/MycnBlogPipeline/MyBlogSystem-III(Deployed)'
    }

    stages {
        stage('Build') {
            steps {
                sh 'env | grep -e PATH -e JAVA_HOME'
                sh 'which java'
                sh 'java --version'
                // dir indicates that the following command will temporarily switch to that directory.
                dir("${env.PROJECT_DIR}") {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                // execute Maven unit tests
                // sh 'mvn test'
                echo 'Testing....'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                // Lauch the java project
                sh '''
                nohup java -jar /home/jenkins/workspace/MycnBlogPipeline/MyBlogSystem-III(Deployed)/target/MyBlogSys.jar \
                > /home/jenkins/workspace/MycnBlogPipeline/MyBlogSystem-III(Deployed)/MyBlogSystem.log &
                '''
            }
        }
    }
}

